#!/usr/bin/env bash
make coverage-generate
if [ $? -ne 0 ]; then
  echo >&2 "Generate coverage failed"
  exit 1
fi

make coverage-upload
if [ $? -ne 0 ]; then
  echo >&2 "Upload coverage failed"
  exit 1
fi