#!/usr/bin/env bash
flutter analyze
if [ $? -ne 0 ]; then
  echo >&2 "Analyze failed"
  exit 1
fi

flutter test
if [ $? -ne 0 ]; then
  echo >&2 "Test failed"
  exit 1
fi

make coverage-generate
if [ $? -ne 0 ]; then
  echo >&2 "Generate coverage failed"
  exit 1
fi

make coverage-upload
if [ $? -ne 0 ]; then
  echo >&2 "Upload coverage failed"
  exit 1
fi