image: cirrusci/flutter:1.22.6

before_script:
  - flutter pub get

stages:
  - analyze-and-test

analyze-and-test:
  stage: analyze-and-test
  script:
    - flutter analyze
    - flutter test --coverage
    - bash <(curl -s https://codecov.io/bash)
